game:
  - internal/game/*
  - internal/game/**/*

config:
  - internal/config/*
  - internal/config/**/*

build:
  - build/*
  - build/**/*

ui:
  - internal/ui/*
  - internal/ui/**/*

ci:
  - .github/*
  - .github/**/*
